# Internal helpers for x_search()
#
# This module implements `x_search()` and its supporting internal functions.
# The search pipeline:
#   1. Enable network capture on the session backend
#   2. Construct the X search URL and navigate
#   3. Wait for network responses to settle
#   4. Retrieve captured network events and extract posts (initial batch)
#   5. Repeat: scroll, wait for new network responses, extract posts
#      — stop on limit, max_scrolls, or no-new-data cycles (Task 42)
#   6. Merge all batches, normalize, convert to tibble, deduplicate
#   7. Apply limit and return
#
# Scroll state (Task 41, Task 42):
#   A scroll state object tracks collection progress across batches.
#   It records seen post IDs, counts, cursors, scroll position, and timing
#   so that repeated-scrolling loops can detect termination conditions
#   (limit hit, max_scrolls exceeded, no-new-data stall) without relying
#   on implicit loop variables.
#
# Observation-level provenance (Task 46):
#   Each post row includes `collected_at`, `collection_query`, and
#   `collection_id` — allowing per-row traceability to the collection
#   that produced it. These are injected before normalization.
#
# Collection provenance (Task 45):
#   Each search result carries collection metadata as an attribute
#   (`rx_collection_provenance`). The metadata is a list with:
#   - collection_id, started_at, query, package_version, backend,
#     parser_version, records
#   This makes the provenance auditable without changing the tibble
#   return type (backward-compatible).
#
# @name search
# @aliases search
# @keywords internal
# @examples
#   # Public API:
#   # sess <- x_session()
#   # posts <- x_search(sess, "r programming")
#   # x_close(sess)
NULL

# ---------------------------------------------------------------------------
# Progress output helper (Task 60)
# ---------------------------------------------------------------------------

#' Emit a progress message to the user.
#'
#' Prints a timestamped message via `message()` when not in quiet mode.
#'
#' @param msg Character string, the progress message.
#' @param quiet Logical, when `TRUE` the message is suppressed.
#' @return Invisible `NULL`.
#' @noRd
.rx_progress <- function(msg, quiet = FALSE) {
  if (isTRUE(quiet)) return(invisible(NULL))
  tryCatch(
    message("[xtweetsR] ", msg),
    error = function(e) NULL
  )
  invisible(NULL)
}

# ---------------------------------------------------------------------------
# Internal constants (Task 64, referenced by Task 45)
# ---------------------------------------------------------------------------

#' Parser version string.
#'
#' Bumped when the parser output schema changes (new fields, removed
#' fields, or field type changes).
#'
#' @return A single-element character vector with the version string.
#' @noRd
.rx_parser_version <- function() "0.1.0"

#' Schema version string.
#'
#' Bumped when the canonical field schema changes.
#'
#' @return A single-element character vector with the version string.
#' @noRd
.rx_schema_version <- function() "0.1.0"

#' Generate a version-4 UUID string.
#'
#' Uses `tools::UUIDgenerate()` when available (R >= 4.4.0), which draws
#' from the OS CSPRNG. Falls back to a `sample()` + `sprintf()` hex
#' generator for older R versions.
#'
#' @return A single-element character vector with a lowercase UUID string.
#' @noRd
.rx_generate_uuid <- function() {
  # Prefer the base-R CSPRNG-backed generator (R >= 4.4.0).
  if (utils::packageVersion("tools") >= "4.4.0") {
    return(tools::UUIDgenerate())
  }

  # Fallback: uniform hex chars via sample() + sprintf("%x") to avoid
  # multi-digit decimal output (e.g. 10 -> "10" instead of "a").
  hex4 <- function() sprintf("%04x", sum(sample(0:15, 4, replace = TRUE) * 16^(3:0)))
  hex2 <- function() sprintf("%02x", sample(0:255, 1, replace = TRUE))
  hex3 <- function() sprintf("%03x", sum(sample(0:15, 3, replace = TRUE) * 16^(2:0)))
  # Version 4: 8-4-4-4-12 = 32 hex chars.
  # Byte 6 top nibble = 4. Variant: byte 8 top 2 bits = 10 (8-b).
  paste0(
    hex4(), hex4(), "-",
    hex4(), "-",
    "4", hex3(), "-",
    sprintf("%02x", sample(8:11, 1, replace = TRUE)), hex2(), "-",
    hex4(), hex4(), hex4()
  )
}

# ---------------------------------------------------------------------------
# Collection provenance (Task 45)
# ---------------------------------------------------------------------------

#' Create collection metadata for a search result.
#'
#' Returns a list containing the provenance of a collection run.
#' The metadata is attached as an attribute to the result tibble so
#' that downstream code can audit how a result was produced without
#' changing the tibble return type.
#'
#' Fields:
#'   - `collection_id`: UUID string generated by `tools::UUIDgenerate()`.
#'   - `started_at`: POSIXct timestamp when the collection began
#'     (taken from the scroll state's `started_at`).
#'   - `query`: The search query string passed to `x_search()`.
#'   - `package_version`: Package version string from DESCRIPTION.
#'   - `backend`: Character description of the backend in use
#'     (e.g. "lightpanda").
#'   - `parser_version`: Internal parser version string.
#'   - `records`: Named integer giving the total post count.
#'
#' @param collection_id Optional character string with a collection ID.
#'   When NULL, a new UUID is generated.
#' @param started_at Optional POSIXct timestamp. When NULL, `Sys.time()`
#'   is used.
#' @param query The search query string.
#' @param backend Character string describing the backend.
#' @param record_count Total number of records (posts) in the result.
#' @return A list of class `rx_collection_provenance`.
#'
#' @examples
#'   \dontrun{
#'     meta <- .rx_collection_metadata(
#'       started_at = Sys.time(),
#'       query = "r programming",
#'       backend = "lightpanda",
#'       record_count = 42
#'     )
#'   }
#'
#' @noRd
.rx_collection_metadata <- function(
  collection_id = NULL,
  started_at = Sys.time(),
  query = "",
  backend = "unknown",
  record_count = 0L
) {
  if (is.null(collection_id) || !is.character(collection_id) || length(collection_id) != 1L) {
    collection_id <- .rx_generate_uuid()
  }

  pkg_version <- tryCatch(
    as.character(utils::packageVersion("xtweetsR")),
    error = function(e) "unknown"
  )

  structure(
    list(
      collection_id   = collection_id,
      started_at      = started_at,
      query           = as.character(query),
      package_version = pkg_version,
      backend         = as.character(backend),
      parser_version  = .rx_parser_version(),
      records         = as.integer(record_count)
    ),
    class = "rx_collection_provenance"
  )
}

#' Print method for collection provenance.
#'
#' @param x The provenance list.
#' @param ... Ignored.
#' @noRd
print.rx_collection_provenance <- function(x, ...) {
  cat("<xtweetsR Collection Provenance>\n")
  cat(sprintf("  collection_id : %s\n", x$collection_id))
  cat(sprintf("  started_at    : %s\n", format(x$started_at)))
  cat(sprintf("  query         : %s\n", x$query))
  cat(sprintf("  package_version: %s\n", x$package_version))
  cat(sprintf("  backend       : %s\n", x$backend))
  cat(sprintf("  parser_version: %s\n", x$parser_version))
  cat(sprintf("  records       : %d\n", x$records))
  invisible(x)
}

#' Search X/Twitter for posts matching a query.
#'
#' Navigates to an X search results page, captures structured network
#' responses, parses and normalizes post objects, deduplicates by
#' \code{post_id}, and returns a tibble of results.
#'
#' This is the first end-to-end search function. It connects the session
#' backend, network capture, post parser, normalizer, and deduplicator
#' into a single call.
#'
#' The collection uses bounded repeated scrolling (Task 42): after the
#' initial extraction, the page is scrolled and new content extracted in a
#' loop. The loop stops when any of the following conditions is met:
#' - the \code{limit} is reached,
#' - \code{max_scrolls} scroll iterations have been completed,
#' - no new data appears for two consecutive batches (stall detection).
#'
#' # Resume support (Task 49)
#' When \code{resume = TRUE} and a checkpoint file exists at
#' \code{checkpoint_path}, the collection restores the previous
#' \code{collection_id}, \code{seen_post_ids}, and cursor state so that
#' already-collected posts are not duplicated.  New posts discovered
#' during the resumed run are appended to the existing JSONL file at
#' \code{jsonl_path}.
#'
#' @param session An \code{xtweetsR_session} object returned by
#'   \code{\link[=x_session]{x_session()}}.
#' @param query A single non-empty character string with the search query.
#' @param limit Optional integer limiting the maximum number of posts
#'   returned. When \code{NULL} (default), no limit is applied.
#' @param scroll Logical, default `TRUE`. When `FALSE`, no scrolling is
#'   performed and only the initially visible content is captured.
#' @param max_scrolls Integer, default `5L`. When \code{scroll = TRUE},
#'   the maximum number of scroll+extract iterations to perform.
#'   The loop also stops earlier if the \code{limit} is reached or if
#'   no new data appears for two consecutive batches.
#' @param resume Logical, default `FALSE`. When `TRUE` and
#'   \code{checkpoint_path} points to an existing checkpoint file,
#'   restore the previous collection state (seen IDs, collection ID,
#'   cursor) and continue from where it left off.
#' @param checkpoint_path Character string with the path to a JSON
#'   checkpoint file (written by \code{.rx_checkpoint_write()}).
#'   When \code{resume = TRUE} and the file exists, its state is loaded.
#'   Defaults to `paste0(query, ".checkpoint.json")` when resuming.
#' @param jsonl_path Character string with the path to the JSONL
#'   collection file. When \code{resume = TRUE}, new posts are appended
#'   to this file instead of overwriting it. Defaults to
#'   `paste0(query, ".jsonl")` when resuming.
#' @param quiet Logical, default `FALSE`. When `TRUE`, progress messages
#'   are suppressed. When `FALSE` (default), the function prints
#'   informational messages at each major step.
#'
#' @return A tibble with the canonical post schema (18 columns) containing
#'   posts found during the search. Returns a zero-row tibble when no
#'   posts are captured.
#'
#' @examples
#' \dontrun{
#'   sess <- x_session()
#'   posts <- x_search(sess, "r programming", limit = 10)
#'   print(posts)
#'   x_close(sess)
#' }
#'
#' @export
x_search <- function(session, query, limit = NULL, scroll = TRUE, max_scrolls = 5L,
                     resume = FALSE, checkpoint_path = NULL, jsonl_path = NULL,
                     quiet = FALSE) {
  # 1. Validate inputs.
  if (!inherits(session, "xtweetsR_session")) {
    stop("session must be an xtweetsR_session object.", call. = FALSE)
  }
  if (!session$connected) {
    stop("Session is not connected. Call x_session() first.", call. = FALSE)
  }
  if (!is.character(query) || length(query) != 1L || anyNA(query) || !nzchar(trimws(query))) {
    stop("query must be a single non-empty character string.", call. = FALSE)
  }
  if (!is.null(limit)) {
    if (!is.numeric(limit) || length(limit) != 1L || anyNA(limit) || limit < 1L) {
      stop("limit must be a positive integer, or NULL.", call. = FALSE)
    }
    limit <- as.integer(limit)
  }
  if (!is.numeric(max_scrolls) || length(max_scrolls) != 1L || anyNA(max_scrolls) || max_scrolls < 0L) {
    stop("max_scrolls must be a non-negative integer, or NULL.", call. = FALSE)
  }
  max_scrolls <- as.integer(max_scrolls)

  # Validate resume-related parameters.
  if (!is.logical(resume) || length(resume) != 1L || anyNA(resume)) {
    stop("resume must be a single logical value.", call. = FALSE)
  }

  if (!is.null(checkpoint_path)) {
    if (!is.character(checkpoint_path) || length(checkpoint_path) != 1L || anyNA(checkpoint_path) || !nzchar(checkpoint_path[[1L]])) {
      stop("checkpoint_path must be a single non-empty character string, or NULL.", call. = FALSE)
    }
  }

  if (!is.null(jsonl_path)) {
    if (!is.character(jsonl_path) || length(jsonl_path) != 1L || anyNA(jsonl_path) || !nzchar(jsonl_path[[1L]])) {
      stop("jsonl_path must be a single non-empty character string, or NULL.", call. = FALSE)
    }
  }

  backend <- session$backend

  # 1b. Resume handling (Task 49).
  # When resume=TRUE and a checkpoint file exists, restore collection state
  # from the checkpoint so that already-seen posts are not duplicated.
  resumed_checkpoint <- NULL
  if (isTRUE(resume)) {
    if (is.null(checkpoint_path)) {
      checkpoint_path <- paste0(gsub("[^A-Za-z0-9._-]", "_", query), ".checkpoint.json")
    }
    if (is.null(jsonl_path)) {
      jsonl_path <- paste0(gsub("[^A-Za-z0-9._-]", "_", query), ".jsonl")
    }

    resumed_checkpoint <- .rx_checkpoint_read(checkpoint_path)
    if (!is.null(resumed_checkpoint)) {
      collection_id <- resumed_checkpoint$collection_id
    }
  }

  # 1c. Capture collection start time and generate collection_id for provenance (Tasks 45, 46).
  collection_started_at <- Sys.time()
  if (is.null(resumed_checkpoint) || is.null(resumed_checkpoint$collection_id)) {
    collection_id <- .rx_generate_uuid()
  }
  backend_label <- "unknown"
  if (inherits(session$backend, "rx_lightpanda_backend")) {
    backend_label <- "lightpanda"
  } else if (inherits(session$backend, "rx_chromium_backend")) {
    backend_label <- "chromium"
  }

  # 2. Enable network capture before navigation.
  tryCatch(
    backend$networkCaptureEnable(),
    error = function(e) {
      stop(.rx_error_network(
        paste0("Failed to enable network capture: ", e$message)
      ))
    }
  )

  # 3. Construct search URL and navigate.
  url <- .rx_construct_search_url(query)

  nav_result <- backend$navigate(url)
  if (is.null(nav_result$status) || nav_result$status == "error") {
    # Navigation failed — still try to return what we can.
    error_info <- if (!is.null(nav_result$error)) nav_result$error$code else "unknown"
    .rx_search_cleanup(backend)
    warning("Navigation failed (", error_info, "). No posts returned.")
  } else {
    .rx_progress("Navigated to ", nav_result$url, quiet = quiet)
  }
    empty <- .rx_search_empty_tibble()
    provenance <- .rx_collection_metadata(
      collection_id = collection_id,
      started_at = collection_started_at,
      query = query,
      backend = backend_label,
      record_count = 0L
    )
    attr(empty, "rx_collection_provenance") <- provenance
    return(empty)
  }

  # 4. Wait for initial network responses to arrive (X search loads content
  #    asynchronously via XHR/GraphQL). A short wait is more reliable
  #    than polling for specific response types.
  Sys.sleep(3)

  # 5. Create scroll state and retrieve initial batch.
  # When resuming, pre-populate seen_post_ids from the checkpoint.
  if (!is.null(resumed_checkpoint) && length(resumed_checkpoint$seen_post_ids) > 0L) {
    state <- .rx_scroll_state_new(seen_post_ids = resumed_checkpoint$seen_post_ids)
  } else {
    state <- .rx_scroll_state_new()
  }

  initial_events <- tryCatch(
    backend$networkCaptureGet(),
    error = function(e) {
      .rx_search_cleanup(backend)
      warning("Failed to retrieve network events: ", e$message)
      return(list())
    }
  )

  initial_posts <- .rx_search_extract_from_events(initial_events, backend)
  state$add_posts(initial_posts)

  .rx_progress(
    "Extracted ", length(initial_posts$post_id), " post(s) from initial batch",
    quiet = quiet
  )

  # 6. Bounded repeated scroll+extract loop (Task 42).
  #
  #    The loop iterates at most max_scrolls times. After each iteration:
  #    - If the limit is reached, we stop.
  #    - If no new data appears for two consecutive batches, we stop.
  #    - After max_scrolls iterations, we stop.
  #
  #    Each iteration scrolls the page, waits for new network responses,
  #    extracts posts, and accumulates them into all_batches.

  # Accumulate initial batch so it is included in the final merge.
  all_batches <- list()
  if (length(initial_posts$post_id) > 0L) {
    all_batches[[1L]] <- initial_posts
  } else {
    all_batches[[1L]] <- .rx_search_empty_batch()
  }
  if (isTRUE(scroll) && max_scrolls > 0L) {
    for (i in seq_len(max_scrolls)) {
      # Scroll the page.
      .rx_scroll_page(backend)
      state$advance_scroll()

      # Wait for new network responses triggered by the scroll.
      Sys.sleep(3)

      # Capture events and extract posts (new batch).
      batch_events <- tryCatch(
        backend$networkCaptureGet(),
        error = function(e) list()
      )

      extracted <- .rx_search_extract_from_events(batch_events, backend)

      # Record in scroll state (dedup, stall detection).
      state$add_posts(extracted)

      .rx_progress(
        "Scroll iteration ", i, ": extracted ", length(extracted$post_id),
        " post(s)",
        quiet = quiet
      )

      # Accumulate batch for later merging.
      if (length(extracted$post_id) > 0L) {
        all_batches[[length(all_batches) + 1L]] <- extracted
      } else {
        # Track zero-length batch to maintain consistent field structure.
        zero_batch <- .rx_search_empty_batch()
        all_batches[[length(all_batches) + 1L]] <- zero_batch
      }

      # Check termination conditions.
      if (!is.null(limit) && state$current_count >= limit) {
        break
      }
      if (state$check_stalled(threshold = 2L)) {
        break
      }
    }
  }

  # 7. Merge all batches (initial + scroll batches).
  if (length(all_batches) > 0L) {
    all_post_ids <- lapply(all_batches, `[[`, "post_id")
    all_texts <- lapply(all_batches, `[[`, "text")
    all_author_ids <- lapply(all_batches, `[[`, "author_id")
    all_usernames <- lapply(all_batches, `[[`, "username")
    all_display_names <- lapply(all_batches, `[[`, "display_name")
    all_created_at <- lapply(all_batches, `[[`, "created_at")
    all_reply_counts <- lapply(all_batches, `[[`, "reply_count")
    all_repost_counts <- lapply(all_batches, `[[`, "repost_count")
    all_like_counts <- lapply(all_batches, `[[`, "like_count")
    all_quote_counts <- lapply(all_batches, `[[`, "quote_count")
    all_bookmark_counts <- lapply(all_batches, `[[`, "bookmark_count")
    all_view_counts <- lapply(all_batches, `[[`, "view_count")
    all_conversation_ids <- lapply(all_batches, `[[`, "conversation_id")
    all_is_replies <- lapply(all_batches, `[[`, "is_reply")
    all_is_reposts <- lapply(all_batches, `[[`, "is_repost")
    all_is_quotes <- lapply(all_batches, `[[`, "is_quote")
    all_reply_to_ids <- lapply(all_batches, `[[`, "reply_to_post_id")
    all_quoted_ids <- lapply(all_batches, `[[`, "quoted_post_id")
    all_hashtags     <- lapply(all_batches, `[[`, "hashtags")
    all_mentions     <- lapply(all_batches, `[[`, "mentions")
    all_urls         <- lapply(all_batches, `[[`, "urls")

    merged_posts <- list(
      post_id        = unlist(all_post_ids, use.names = FALSE),
      text           = unlist(all_texts, use.names = FALSE),
      author_id      = unlist(all_author_ids, use.names = FALSE),
      username       = unlist(all_usernames, use.names = FALSE),
      display_name   = unlist(all_display_names, use.names = FALSE),
      created_at     = unlist(all_created_at, use.names = FALSE),
      reply_count    = unlist(all_reply_counts, use.names = FALSE),
      repost_count   = unlist(all_repost_counts, use.names = FALSE),
      like_count     = unlist(all_like_counts, use.names = FALSE),
      quote_count    = unlist(all_quote_counts, use.names = FALSE),
      bookmark_count = unlist(all_bookmark_counts, use.names = FALSE),
      view_count     = unlist(all_view_counts, use.names = FALSE),
      conversation_id = unlist(all_conversation_ids, use.names = FALSE),
      is_reply       = unlist(all_is_replies, use.names = FALSE),
      is_repost      = unlist(all_is_reposts, use.names = FALSE),
      is_quote       = unlist(all_is_quotes, use.names = FALSE),
      reply_to_post_id = unlist(all_reply_to_ids, use.names = FALSE),
      quoted_post_id   = unlist(all_quoted_ids, use.names = FALSE),
      # Entity fields (Task 56)
      hashtags       = unlist(all_hashtags, recursive = FALSE),
      mentions       = unlist(all_mentions, recursive = FALSE),
      urls           = unlist(all_urls, recursive = FALSE)
    )
  } else {
    # No batches collected at all (scroll=FALSE, no initial posts).
    merged_posts <- list(
      post_id        = character(0),
      text           = character(0),
      author_id      = character(0),
      username       = character(0),
      display_name   = character(0),
      created_at     = character(0),
      reply_count    = integer(0),
      repost_count   = integer(0),
      like_count     = integer(0),
      quote_count    = integer(0),
      bookmark_count = integer(0),
      view_count     = integer(0),
      conversation_id = character(0),
      is_reply       = logical(0),
      is_repost      = logical(0),
      is_quote       = logical(0),
      reply_to_post_id = character(0),
      quoted_post_id   = character(0),
      # Entity fields (Task 56)
      hashtags       = list(),
      mentions       = list(),
      urls           = list()
    )
  }

  # 7b. Observation-level provenance (Task 46).
  # Populate collected_at, collection_query, collection_id for every row.
  n_merged <- if (length(merged_posts$post_id) > 0L) length(merged_posts$post_id) else 0L
  merged_posts$collected_at     <- rep(format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), n_merged)
  merged_posts$collection_query <- rep(query, n_merged)
  merged_posts$collection_id    <- rep(collection_id, n_merged)

  # 8. Normalize, convert to tibble, deduplicate.
  normalized <- .rx_normalize_posts(merged_posts)
  tibble_posts <- .rx_normalized_to_tibble(normalized)
  deduped <- .rx_deduplicate_posts(tibble_posts)

  # 9. Apply limit.
  if (!is.null(limit) && nrow(deduped) > limit) {
    deduped <- deduped[seq_len(limit), , drop = FALSE]
  }

  # 10. Clean up network capture.
  .rx_search_cleanup(backend)

  # 10b. Write checkpoint for resume support (Task 49).
  # Persist the current state so that a future call with resume=TRUE
  # can continue from where we left off. The checkpoint is always
  # written (overwriting any previous checkpoint) since it represents
  # the latest state.
  if (isTRUE(resume) && !is.null(jsonl_path)) {
    checkpoint <- .rx_checkpoint_from_state(state, collection_id, query)
    tryCatch(
      {
        .rx_checkpoint_write(jsonl_path, checkpoint)
        .rx_progress("Checkpoint saved to ", jsonl_path, quiet = quiet)
      },
      error = function(e) {
        warning("Failed to write checkpoint to '", jsonl_path, "': ", e$message)
      }
    )
  }

  # 11. Attach collection provenance metadata (Tasks 45, 46).
  provenance <- .rx_collection_metadata(
    collection_id = collection_id,
    started_at = collection_started_at,
    query = query,
    backend = backend_label,
    record_count = as.integer(nrow(deduped))
  )
  attr(deduped, "rx_collection_provenance") <- provenance

  .rx_progress(
    "Collection complete: ", nrow(deduped), " post(s) in ",
    round(as.numeric(difftime(Sys.time(), collection_started_at, units = "secs")), 1),
    "s",
    quiet = quiet
  )

  deduped
}

# ---------------------------------------------------------------------------
# x_post() — Individual post navigation (Task 54)
# ---------------------------------------------------------------------------

#' Fetch a single post by its URL or post ID.
#'
#' Navigates to an X post URL (or a bare post ID), captures structured
#' network responses from that single post page, parses and normalizes
#' the post object, and returns a one-row tibble.
#'
#' This is the simplest entry point for post-level data collection.
#' Unlike \code{\link[=x_search]{x_search()}} or \code{\link[=x_user_posts]{x_user_posts()}},
#' it does not scroll — it captures whatever structured data is
#' available on the single post page.
#'
#' @param session An \code{xtweetsR_session} object returned by
#'   \code{\link[=x_session]{x_session()}}.
#' @param post_id A single character string that is either a full X
#'   post URL (e.g. `https://x.com/rstudio/status/1234567890`) or a
#'   bare post ID (e.g. `1234567890123456789`).
#' @param limit Optional integer limiting the maximum number of posts
#'   returned. Default `1L` — a single post page should yield at most
#'   one post.
#' @param quiet Logical, default `FALSE`. When `TRUE`, progress messages
#'   are suppressed.
#'
#' @return A tibble with the canonical post schema (21 columns)
#'   containing zero or one row. Returns a zero-row tibble when no
#'   post data is captured.
#'
#' @examples
#' \dontrun{
#'   sess <- x_session()
#'   post <- x_post(sess, "1234567890123456789")
#'   print(post)
#'   x_close(sess)
#' }
#'
#' @export
x_post <- function(session, post_id, limit = 1L, quiet = FALSE) {
  # 1. Validate inputs.
  if (!inherits(session, "xtweetsR_session")) {
    stop("session must be an xtweetsR_session object.", call. = FALSE)
  }
  if (!session$connected) {
    stop("Session is not connected. Call x_session() first.", call. = FALSE)
  }
  if (!is.character(post_id) || length(post_id) != 1L || anyNA(post_id) || !nzchar(trimws(post_id))) {
    stop("post_id must be a single non-empty character string (URL or post ID).", call. = FALSE)
  }
  if (!is.numeric(limit) || length(limit) != 1L || anyNA(limit) || limit < 1L) {
    stop("limit must be a positive integer.", call. = FALSE)
  }
  limit <- as.integer(limit)

  backend <- session$backend

  # 1b. Normalize the post identifier to a canonical URL.
  url <- .rx_normalize_post_url(post_id)

  # 1c. Capture collection start time and generate collection_id for provenance.
  collection_started_at <- Sys.time()
  collection_id <- .rx_generate_uuid()
  backend_label <- "unknown"
  if (inherits(session$backend, "rx_lightpanda_backend")) {
    backend_label <- "lightpanda"
  } else if (inherits(session$backend, "rx_chromium_backend")) {
    backend_label <- "chromium"
  }

  # 2. Enable network capture before navigation.
  tryCatch(
    backend$networkCaptureEnable(),
    error = function(e) {
      stop(.rx_error_network(
        paste0("Failed to enable network capture: ", e$message)
      ))
    }
  )

  # 3. Navigate to the post.
  nav_result <- backend$navigate(url)
  if (is.null(nav_result$status) || nav_result$status == "error") {
    # Navigation failed — return empty tibble.
    error_info <- if (!is.null(nav_result$error)) nav_result$error$code else "unknown"
    .rx_search_cleanup(backend)
    warning("Navigation failed (", error_info, "). No post returned.")
  } else {
    .rx_progress("Navigated to ", nav_result$url, quiet = quiet)
  }
    empty <- .rx_search_empty_tibble()
    provenance <- .rx_collection_metadata(
      collection_id = collection_id,
      started_at = collection_started_at,
      query = paste0("post:", trimws(post_id)),
      backend = backend_label,
      record_count = 0L
    )
    attr(empty, "rx_collection_provenance") <- provenance
    return(empty)
  }

  # 4. Wait for network responses to arrive (post pages load asynchronously).
  Sys.sleep(3)

  # 5. Capture events and extract posts from the single post page.
  events <- tryCatch(
    backend$networkCaptureGet(),
    error = function(e) {
      .rx_search_cleanup(backend)
      warning("Failed to retrieve network events: ", e$message)
      return(list())
    }
  )

  posts <- .rx_search_extract_from_events(events, backend)

  # 5b. Observation-level provenance.
  n_posts <- if (length(posts$post_id) > 0L) length(posts$post_id) else 0L
  posts$collected_at     <- rep(format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), n_posts)
  posts$collection_query <- rep(paste0("post:", trimws(post_id)), n_posts)
  posts$collection_id    <- rep(collection_id, n_posts)

  # 6. Normalize, convert to tibble, deduplicate.
  normalized <- .rx_normalize_posts(posts)
  tibble_posts <- .rx_normalized_to_tibble(normalized)
  deduped <- .rx_deduplicate_posts(tibble_posts)

  # 7. Apply limit (should be 1 by default).
  if (nrow(deduped) > limit) {
    deduped <- deduped[seq_len(limit), , drop = FALSE]
  }

  # 8. Clean up network capture.
  .rx_search_cleanup(backend)

  # 9. Attach collection provenance metadata.
  provenance <- .rx_collection_metadata(
    collection_id = collection_id,
    started_at = collection_started_at,
    query = paste0("post:", trimws(post_id)),
    backend = backend_label,
    record_count = as.integer(nrow(deduped))
  )
  attr(deduped, "rx_collection_provenance") <- provenance

  .rx_progress(
    "Post lookup complete: ", nrow(deduped), " post(s)",
    quiet = quiet
  )

  deduped
}

#' Return an empty batch with the canonical field structure.
#'
#' Used to maintain consistent field structure when a scroll iteration
#' produces zero posts (no-new-data cycle).
#'
#' @return A list with 26 canonical fields, all empty vectors.
#' @noRd
.rx_search_empty_batch <- function() {
  list(
    post_id        = character(0),
    text           = character(0),
    author_id      = character(0),
    username       = character(0),
    display_name   = character(0),
    created_at     = character(0),
    reply_count    = integer(0),
    repost_count   = integer(0),
    like_count     = integer(0),
    quote_count    = integer(0),
    bookmark_count = integer(0),
    view_count     = integer(0),
    conversation_id = character(0),
    is_reply       = logical(0),
    is_repost      = logical(0),
    is_quote       = logical(0),
    reply_to_post_id = character(0),
    quoted_post_id   = character(0),
    # Entity fields (Task 56)
    hashtags         = list(),
    mentions         = list(),
    urls             = list(),
    # Observation-level provenance (Task 46)
    collected_at     = character(0),
    collection_query = character(0),
    collection_id    = character(0)
  )
}

#' Clean up network capture resources after a search.
#'
#' @param backend The backend object.
#' @noRd
.rx_search_cleanup <- function(backend) {
  tryCatch(backend$networkCaptureClear(), error = function(e) NULL)
}

#' Create an empty tibble with zero rows and the canonical schema.
#'
#' @return A tibble with 26 columns matching the canonical schema,
#'   zero rows.
#' @noRd
.rx_search_empty_tibble <- function() {
  fields <- .rx_canonical_fields()
  type_map <- .rx_type_map()
  cols <- lapply(fields, function(f) {
    switch(type_map[[f]],
      character = character(0),
      integer = integer(0),
      logical = logical(0),
      list      = list()
    )
  })
  names(cols) <- fields
  tibble::as_tibble(cols)
}

#' Extract posts from captured network events.
#'
#' Walks the network events, identifies candidate JSON responses
#' (X domain + application/json), fetches their bodies, parses
#' JSON, extracts posts, and accumulates them.
#'
#' @param events A list of network event records.
#' @param backend The backend object for fetching response bodies.
#' @return A parsed posts list (as from `.rx_parse_posts()`).
#' @noRd
.rx_search_extract_from_events <- function(events, backend) {
  all_parsed <- list(
    post_id = character(0), text = character(0),
    author_id = character(0), username = character(0),
    display_name = character(0), created_at = character(0),
    reply_count = integer(0), repost_count = integer(0),
    like_count = integer(0), quote_count = integer(0),
    bookmark_count = integer(0), view_count = integer(0),
    conversation_id = character(0),
    is_reply = logical(0), is_repost = logical(0), is_quote = logical(0),
    reply_to_post_id = character(0), quoted_post_id = character(0),
    # Entity fields (Task 56)
    hashtags = list(), mentions = list(), urls = list(),
    # Observation-level provenance (Task 46) — placeholders;
    # populated later from search context.
    collected_at = character(0),
    collection_query = character(0),
    collection_id = character(0)
  )

  # Collect candidate event IDs: X domain + JSON content type.
  candidate_ids <- character(0)
  for (evt in events) {
    if (!.rx_search_is_candidate(evt)) {
      next
    }
    candidate_ids <- c(candidate_ids, evt$requestId)
  }

  # For each candidate, fetch the response body and parse.
  for (req_id in candidate_ids) {
    body_result <- tryCatch(
      backend$networkCaptureGetBody(req_id),
      error = function(e) list(error = e$message)
    )

    # Skip if body fetch failed.
    if (!is.null(body_result$error)) {
      next
    }

    # body may already be a parsed list (sidecar auto-parses JSON).
    body <- body_result$body

    # Attempt to parse if it's a string.
    if (is.character(body) && length(body) == 1L && nzchar(body[[1]])) {
      parsed_json <- tryCatch(
        jsonlite::fromJSON(body[[1]], simplifyVector = FALSE),
        error = function(e) NULL
      )
      if (!is.null(parsed_json)) {
        body <- parsed_json
      }
    }

    # Skip if not a list.
    if (!is.list(body)) {
      next
    }

    # Try to extract posts from this response.
    parsed <- .rx_parse_posts(body)
    if (length(parsed$post_id) == 0L) {
      next
    }

    # Append to accumulated results.
    all_parsed$post_id      <- c(all_parsed$post_id,      parsed$post_id)
    all_parsed$text         <- c(all_parsed$text,         parsed$text)
    all_parsed$author_id    <- c(all_parsed$author_id,    parsed$author_id)
    all_parsed$username     <- c(all_parsed$username,     parsed$username)
    all_parsed$display_name <- c(all_parsed$display_name, parsed$display_name)
    all_parsed$created_at   <- c(all_parsed$created_at,   parsed$created_at)
    all_parsed$reply_count  <- c(all_parsed$reply_count,  parsed$reply_count)
    all_parsed$repost_count <- c(all_parsed$repost_count, parsed$repost_count)
    all_parsed$like_count   <- c(all_parsed$like_count,   parsed$like_count)
    all_parsed$quote_count  <- c(all_parsed$quote_count,  parsed$quote_count)
    all_parsed$bookmark_count <- c(all_parsed$bookmark_count, parsed$bookmark_count)
    all_parsed$view_count   <- c(all_parsed$view_count,   parsed$view_count)
    all_parsed$conversation_id <- c(all_parsed$conversation_id, parsed$conversation_id)
    all_parsed$is_reply     <- c(all_parsed$is_reply,     parsed$is_reply)
    all_parsed$is_repost    <- c(all_parsed$is_repost,    parsed$is_repost)
    all_parsed$is_quote     <- c(all_parsed$is_quote,     parsed$is_quote)
    all_parsed$reply_to_post_id <- c(all_parsed$reply_to_post_id, parsed$reply_to_post_id)
    all_parsed$quoted_post_id   <- c(all_parsed$quoted_post_id,   parsed$quoted_post_id)
    # Entity fields (Task 56).
    all_parsed$hashtags <- c(all_parsed$hashtags, parsed$hashtags)
    all_parsed$mentions <- c(all_parsed$mentions, parsed$mentions)
    all_parsed$urls     <- c(all_parsed$urls,     parsed$urls)
  }

  all_parsed
}

#' Check whether a network event is a candidate post-bearing response.
#'
#' A candidate is an event from the X/Twitter domain with a JSON
#' content type. This is a heuristic filter — not all JSON responses
#' from X contain posts, but post-bearing responses will match.
#'
#' @param evt A network event record (from `networkCaptureGet()`).
#' @return Logical, TRUE when the event is a candidate.
#' @noRd
.rx_search_is_candidate <- function(evt) {
  if (!is.list(evt)) return(FALSE)

  url <- evt$url
  if (is.null(url) || !is.character(url) || length(url) != 1L) return(FALSE)

  # Must be from the X/Twitter domain.
  if (!grepl("x\\.com|twitter\\.com", url, ignore.case = TRUE)) {
    return(FALSE)
  }

  # Must have a JSON content type (check contentType or inferred from URL).
  content_type <- evt$contentType
  if (!is.null(content_type) && is.character(content_type) && length(content_type) == 1L) {
    if (grepl("application/json|text/json", content_type, ignore.case = TRUE)) {
      return(TRUE)
    }
  }

  # Also check if the URL path looks like an API/GraphQL endpoint.
  if (grepl("/graphql|/internal\\.alg\\.com", url, ignore.case = TRUE)) {
    return(TRUE)
  }

  FALSE
}

#' Scroll the page downward to trigger loading of more content.
#'
#' Executes a JavaScript scroll expression in the current page.
#' This is the standard pattern for infinite-scroll pages like X/Twitter:
#' scroll down by a large amount, wait for content to load.
#'
#' The scroll is wrapped in `tryCatch` so that scroll failures are
#' non-fatal — the search returns whatever was captured before the scroll.
#'
#' @param backend The backend object (must support `$evaluate()`).
#' @noRd
.rx_scroll_page <- function(backend) {
  tryCatch(
    backend$evaluate(
      # Scroll by 4000px; X/Twitter uses IntersectionObserver-based lazy
      # loading, so scrolling far enough triggers new content requests.
      "window.scrollBy(0, 4000)"
    ),
    error = function(e) {
      # Scroll is best-effort — a failed evaluation (e.g. page closed)
      # should not break the search pipeline.
      invisible(NULL)
    }
  )
}

# ---------------------------------------------------------------------------
# Scroll state object (Task 41)
# ---------------------------------------------------------------------------

#' Create a scroll state object.
#'
#' Tracks collection progress across batches so that repeated-scrolling loops
#' can make data-driven decisions about termination, deduplication, and
#' pacing. This replaces implicit loop variables with an explicit state
#' record that can be inspected, serialized, and extended.
#'
#' The state object is an environment (reference semantics) so method calls
#' mutate in place without needing reassignment. Fields are stored directly
#' on the environment; methods are closures that close over it.
#'
#' @param seen_post_ids Optional character vector of post IDs already seen.
#'   When provided (e.g. from a checkpoint during resume), the state is
#'   initialized with these IDs and `current_count` reflects them.
#' @param last_cursor Optional character string with the cursor from the
#'   last network response. Used to continue cursor-based pagination.
#' @param records_collected Optional integer count of records already
#'   collected. When resuming from a checkpoint, this reflects the
#'   persisted count.
#' @return An environment of class `rx_scroll_state` with method functions
#'   attached (`add_posts`, `advance_scroll`, `check_stalled`, `check_limit`).
#'
#' @examples
#' \dontrun{
#'   state <- .rx_scroll_state_new()
#'   state$add_posts(list(post_id = c("1", "2", "3")))
#'   state$check_stalled()
#' }
#'
#' @noRd
.rx_scroll_state_new <- function(seen_post_ids = character(0), last_cursor = "", records_collected = NULL) {
  count <- if (is.null(records_collected) || !is.numeric(records_collected)) {
    length(seen_post_ids)
  } else {
    as.integer(records_collected)
  }

  # Environment gives reference semantics: method closures mutate the
  # same object instead of working on a copy-by-value list.
  env <- new.env(parent = emptyenv())

  # State fields.
  env$seen_post_ids     <- as.character(seen_post_ids)
  env$current_count     <- as.integer(count)
  env$previous_count    <- 0L
  env$no_new_data_cycles <- 0L
  env$scroll_position   <- 0
  env$last_post_id      <- ""
  env$last_cursor       <- as.character(last_cursor)
  env$started_at        <- Sys.time()
  env$elapsed_time      <- 0

  # Methods — closures that close over `env`, so every mutation is visible
  # to callers without needing reassignment.

  env$add_posts <- function(posts, new_cursor = "") {
    .rx_scroll_state_add_posts(env, posts, new_cursor)
    invisible(env)
  }

  env$advance_scroll <- function(pixels = 4000) {
    .rx_scroll_state_advance_scroll(env, pixels)
    invisible(env)
  }

  env$check_stalled <- function(threshold = 2L) {
    .rx_scroll_state_check_stalled(env, threshold)
  }

  env$check_limit <- function(limit) {
    .rx_scroll_state_check_limit(env, limit)
  }

  class(env) <- "rx_scroll_state"
  env
}

#' Add a batch of posts to the scroll state.
#'
#' Updates `seen_post_ids`, `current_count`, `previous_count`,
#' `no_new_data_cycles`, `last_post_id`, and `elapsed_time` based on
#' the new batch content. Called after each batch extraction.
#'
#' @param state An `rx_scroll_state` object (modified in place).
#' @param posts A list of post fields with at least a `post_id` element,
#'   as returned by `.rx_parse_posts()`.
#' @param new_cursor Optional character string with a cursor extracted from
#'   the network response that produced this batch.
#' @return The modified state object (in place; returned for chaining).
#'
#' @examples
#' \dontrun{
#'   state <- .rx_scroll_state_new()
#'   state$add_posts(list(post_id = c("1", "2")))
#'   state$add_posts(list(post_id = c("2", "3")), new_cursor = "cursor-abc")
#' }
#'
#' @noRd
.rx_scroll_state_add_posts <- function(state, posts, new_cursor = "") {
  # Update elapsed time.
  state$elapsed_time <- as.numeric(difftime(Sys.time(), state$started_at, units = "secs"))

  # Save previous count before updating.
  state$previous_count <- state$current_count

  # Extract post IDs from the batch.
  batch_ids <- if (is.list(posts) && !is.null(posts$post_id)) {
    posts$post_id
  } else {
    character(0)
  }

  # Filter to only IDs we haven't seen yet.
  new_ids <- batch_ids[!batch_ids %in% state$seen_post_ids]

  # Update seen_post_ids and count.
  if (length(new_ids) > 0L) {
    state$seen_post_ids <- c(state$seen_post_ids, new_ids)
    state$current_count <- length(state$seen_post_ids)
    # Reset stall counter on new data.
    state$no_new_data_cycles <- 0L
    # Track first post ID of this batch.
    state$last_post_id <- new_ids[[1L]]
  } else {
    # No new data — increment stall counter.
    state$no_new_data_cycles <- state$no_new_data_cycles + 1L
  }

  # Update cursor if provided.
  if (is.character(new_cursor) && length(new_cursor) == 1L && nzchar(new_cursor)) {
    state$last_cursor <- new_cursor
  }

  invisible(state)
}

#' Check whether the collection has stalled.
#'
#' Returns TRUE when `no_new_data_cycles` exceeds the given threshold.
#' This is the primary termination signal for repeated-scrolling loops.
#'
#' @param state An `rx_scroll_state` object.
#' @param threshold Integer, maximum allowed consecutive no-new-data cycles
#'   before considering the collection stalled. Default is 2L.
#' @return Logical, TRUE when the collection should stop scrolling.
#' @noRd
#'
#' @examples
#' \dontrun{
#'   state <- .rx_scroll_state_new()
#'   state$add_posts(list(post_id = c("1")))
#'   state$check_stalled()              # FALSE
#'   state$add_posts(list(post_id = c("1")))  # duplicate only
#'   state$check_stalled()              # FALSE
#'   state$add_posts(list(post_id = character(0)))
#'   state$check_stalled(threshold = 1) # TRUE
#' }
#'
#' @noRd
.rx_scroll_state_check_stalled <- function(state, threshold = 2L) {
  state$no_new_data_cycles >= threshold
}

#' Check whether the collection has reached the limit.
#'
#' Returns TRUE when `current_count` is at or above the given limit.
#'
#' @param state An `rx_scroll_state` object.
#' @param limit Integer limit on the number of posts to collect.
#' @return Logical, TRUE when the limit has been reached.
#' @noRd
#'
#' @examples
#' \dontrun{
#'   state <- .rx_scroll_state_new()
#'   state$add_posts(list(post_id = c("1", "2", "3")))
#'   state$check_limit(3)  # TRUE
#'   state$check_limit(2)  # FALSE
#' }
#'
#' @noRd
.rx_scroll_state_check_limit <- function(state, limit) {
  !is.null(limit) && state$current_count >= limit
}

#' Advance the scroll position in the state.
#'
#' Increments `scroll_position` by the given pixel amount.
#'
#' @param state An `rx_scroll_state` object.
#' @param pixels Numeric pixel offset to add. Default is 4000 (standard scroll).
#' @return The modified state object (in place).
#' @noRd
#'
#' @examples
#' \dontrun{
#'   state <- .rx_scroll_state_new()
#'   state$advance_scroll(1000)
#'   state$advance_scroll(3000)
#'   state$scroll_position  # 4000
#' }
#'
#' @noRd
.rx_scroll_state_advance_scroll <- function(state, pixels = 4000) {
  state$scroll_position <- state$scroll_position + pixels
  invisible(state)
}

# ---------------------------------------------------------------------------
# x_user_posts() — User timeline navigation layer (Task 52)
# ---------------------------------------------------------------------------

#' Fetch posts from a specific user's timeline.
#'
#' Navigates to an X user timeline page, captures structured network
#' responses, parses and normalizes post objects, deduplicates by
#' \code{post_id}, and returns a tibble of results.
#'
#' This is the user-timeline equivalent of \code{\link[=x_search]{x_search()}}.
#' It reuses the same session/backend, network capture, parser, normalizer,
#' and deduplicator — only the navigation target differs.
#'
#' @param session An \code{xtweetsR_session} object returned by
#'   \code{\link[=x_session]{x_session()}}.
#' @param username A single non-empty character string with an X
#'   username (without the leading @).
#' @param limit Optional integer limiting the maximum number of posts
#'   returned. When \code{NULL} (default), no limit is applied.
#' @param path Optional path segment appended after the username,
#'   e.g. `"media"`, `"tweets_with_replies"`, `"following"`,
#'   `"followers"`. When \code{NULL}, the base timeline is used.
#' @param scroll Logical, default `TRUE`. When `FALSE`, no scrolling
#'   is performed and only the initially visible content is captured.
#' @param max_scrolls Integer, default `5L`. When \code{scroll = TRUE},
#'   the maximum number of scroll+extract iterations to perform.
#' @param resume Logical, default `FALSE`. When `TRUE` and
#'   \code{checkpoint_path} points to an existing checkpoint file,
#'   restore the previous collection state.
#' @param checkpoint_path Character string with the path to a JSON
#'   checkpoint file. Defaults to
#'   `paste0(gsub("[^A-Za-z0-9._-]", "_", username), ".checkpoint.json")`
#'   when resuming.
#' @param jsonl_path Character string with the path to the JSONL
#'   collection file. Defaults to
#'   `paste0(gsub("[^A-Za-z0-9._-]", "_", username), ".jsonl")`
#'   when resuming.
#' @param quiet Logical, default `FALSE`. When `TRUE`, progress messages
#'   are suppressed. When `FALSE` (default), the function prints
#'   informational messages at each major step.
#'
#' @return A tibble with the canonical post schema (21 columns) containing
#'   posts found on the user's timeline. Returns a zero-row tibble when
#'   no posts are captured.
#'
#' @examples
#' \dontrun{
#'   sess <- x_session()
#'   posts <- x_user_posts(sess, "hadleywickham", limit = 10)
#'   print(posts)
#'   x_close(sess)
#' }
#'
#' @export
x_user_posts <- function(session, username, limit = NULL, path = NULL,
                         scroll = TRUE, max_scrolls = 5L,
                         resume = FALSE, checkpoint_path = NULL, jsonl_path = NULL,
                         quiet = FALSE) {
  # 1. Validate inputs.
  if (!inherits(session, "xtweetsR_session")) {
    stop("session must be an xtweetsR_session object.", call. = FALSE)
  }
  if (!session$connected) {
    stop("Session is not connected. Call x_session() first.", call. = FALSE)
  }
  if (!is.character(username) || length(username) != 1L || anyNA(username) || !nzchar(trimws(username))) {
    stop("username must be a single non-empty character string.", call. = FALSE)
  }
  if (!is.null(limit)) {
    if (!is.numeric(limit) || length(limit) != 1L || anyNA(limit) || limit < 1L) {
      stop("limit must be a positive integer, or NULL.", call. = FALSE)
    }
    limit <- as.integer(limit)
  }
  if (!is.numeric(max_scrolls) || length(max_scrolls) != 1L || anyNA(max_scrolls) || max_scrolls < 0L) {
    stop("max_scrolls must be a non-negative integer, or NULL.", call. = FALSE)
  }
  max_scrolls <- as.integer(max_scrolls)

  # Validate resume-related parameters.
  if (!is.logical(resume) || length(resume) != 1L || anyNA(resume)) {
    stop("resume must be a single logical value.", call. = FALSE)
  }

  if (!is.null(checkpoint_path)) {
    if (!is.character(checkpoint_path) || length(checkpoint_path) != 1L || anyNA(checkpoint_path) || !nzchar(checkpoint_path[[1L]])) {
      stop("checkpoint_path must be a single non-empty character string, or NULL.", call. = FALSE)
    }
  }

  if (!is.null(jsonl_path)) {
    if (!is.character(jsonl_path) || length(jsonl_path) != 1L || anyNA(jsonl_path) || !nzchar(jsonl_path[[1L]])) {
      stop("jsonl_path must be a single non-empty character string, or NULL.", call. = FALSE)
    }
  }

  backend <- session$backend

  # 1b. Resume handling (same pattern as x_search).
  resumed_checkpoint <- NULL
  if (isTRUE(resume)) {
    if (is.null(checkpoint_path)) {
      checkpoint_path <- paste0(gsub("[^A-Za-z0-9._-]", "_", username), ".checkpoint.json")
    }
    if (is.null(jsonl_path)) {
      jsonl_path <- paste0(gsub("[^A-Za-z0-9._-]", "_", username), ".jsonl")
    }

    resumed_checkpoint <- .rx_checkpoint_read(checkpoint_path)
    if (!is.null(resumed_checkpoint)) {
      collection_id <- resumed_checkpoint$collection_id
    }
  }

  # 1c. Capture collection start time and generate collection_id for provenance.
  collection_started_at <- Sys.time()
  if (is.null(resumed_checkpoint) || is.null(resumed_checkpoint$collection_id)) {
    collection_id <- .rx_generate_uuid()
  }
  backend_label <- "unknown"
  if (inherits(session$backend, "rx_lightpanda_backend")) {
    backend_label <- "lightpanda"
  } else if (inherits(session$backend, "rx_chromium_backend")) {
    backend_label <- "chromium"
  }

  # 2. Enable network capture before navigation.
  tryCatch(
    backend$networkCaptureEnable(),
    error = function(e) {
      stop(.rx_error_network(
        paste0("Failed to enable network capture: ", e$message)
      ))
    }
  )

  # 3. Construct user timeline URL and navigate.
  url <- .rx_construct_user_timeline_url(username, path = path)

  nav_result <- backend$navigate(url)
  if (is.null(nav_result$status) || nav_result$status == "error") {
    # Navigation failed — still try to return what we can.
    error_info <- if (!is.null(nav_result$error)) nav_result$error$code else "unknown"
    .rx_search_cleanup(backend)
    warning("Navigation failed (", error_info, "). No posts returned.")
  } else {
    .rx_progress("Navigated to ", nav_result$url, quiet = quiet)
  }
    empty <- .rx_search_empty_tibble()
    provenance <- .rx_collection_metadata(
      collection_id = collection_id,
      started_at = collection_started_at,
      query = paste0("@", trimws(username)),
      backend = backend_label,
      record_count = 0L
    )
    attr(empty, "rx_collection_provenance") <- provenance
    return(empty)
  }

  # 4. Wait for initial network responses to arrive.
  Sys.sleep(3)

  # 5. Create scroll state and retrieve initial batch.
  if (!is.null(resumed_checkpoint) && length(resumed_checkpoint$seen_post_ids) > 0L) {
    state <- .rx_scroll_state_new(seen_post_ids = resumed_checkpoint$seen_post_ids)
  } else {
    state <- .rx_scroll_state_new()
  }

  initial_events <- tryCatch(
    backend$networkCaptureGet(),
    error = function(e) {
      .rx_search_cleanup(backend)
      warning("Failed to retrieve network events: ", e$message)
      return(list())
    }
  )

  initial_posts <- .rx_search_extract_from_events(initial_events, backend)
  state$add_posts(initial_posts)

  .rx_progress(
    "Extracted ", length(initial_posts$post_id), " post(s) from initial batch",
    quiet = quiet
  )

  # Accumulate initial batch.
  all_batches <- list()
  if (length(initial_posts$post_id) > 0L) {
    all_batches[[1L]] <- initial_posts
  } else {
    all_batches[[1L]] <- .rx_search_empty_batch()
  }

  # 6. Bounded repeated scroll+extract loop (same pattern as x_search).
  if (isTRUE(scroll) && max_scrolls > 0L) {
    for (i in seq_len(max_scrolls)) {
      .rx_scroll_page(backend)
      state$advance_scroll()

      Sys.sleep(3)

      batch_events <- tryCatch(
        backend$networkCaptureGet(),
        error = function(e) list()
      )

      extracted <- .rx_search_extract_from_events(batch_events, backend)
      state$add_posts(extracted)

      .rx_progress(
        "Scroll iteration ", i, ": extracted ", length(extracted$post_id),
        " post(s)",
        quiet = quiet
      )

      if (length(extracted$post_id) > 0L) {
        all_batches[[length(all_batches) + 1L]] <- extracted
      } else {
        zero_batch <- .rx_search_empty_batch()
        all_batches[[length(all_batches) + 1L]] <- zero_batch
      }

      if (!is.null(limit) && state$current_count >= limit) {
        break
      }
      if (state$check_stalled(threshold = 2L)) {
        break
      }
    }
  }

  # 7. Merge all batches.
  if (length(all_batches) > 0L) {
    all_post_ids <- lapply(all_batches, `[[`, "post_id")
    all_texts <- lapply(all_batches, `[[`, "text")
    all_author_ids <- lapply(all_batches, `[[`, "author_id")
    all_usernames <- lapply(all_batches, `[[`, "username")
    all_display_names <- lapply(all_batches, `[[`, "display_name")
    all_created_at <- lapply(all_batches, `[[`, "created_at")
    all_reply_counts <- lapply(all_batches, `[[`, "reply_count")
    all_repost_counts <- lapply(all_batches, `[[`, "repost_count")
    all_like_counts <- lapply(all_batches, `[[`, "like_count")
    all_quote_counts <- lapply(all_batches, `[[`, "quote_count")
    all_bookmark_counts <- lapply(all_batches, `[[`, "bookmark_count")
    all_view_counts <- lapply(all_batches, `[[`, "view_count")
    all_conversation_ids <- lapply(all_batches, `[[`, "conversation_id")
    all_is_replies <- lapply(all_batches, `[[`, "is_reply")
    all_is_reposts <- lapply(all_batches, `[[`, "is_repost")
    all_is_quotes <- lapply(all_batches, `[[`, "is_quote")
    all_reply_to_ids <- lapply(all_batches, `[[`, "reply_to_post_id")
    all_quoted_ids <- lapply(all_batches, `[[`, "quoted_post_id")
    all_hashtags     <- lapply(all_batches, `[[`, "hashtags")
    all_mentions     <- lapply(all_batches, `[[`, "mentions")
    all_urls         <- lapply(all_batches, `[[`, "urls")

    merged_posts <- list(
      post_id        = unlist(all_post_ids, use.names = FALSE),
      text           = unlist(all_texts, use.names = FALSE),
      author_id      = unlist(all_author_ids, use.names = FALSE),
      username       = unlist(all_usernames, use.names = FALSE),
      display_name   = unlist(all_display_names, use.names = FALSE),
      created_at     = unlist(all_created_at, use.names = FALSE),
      reply_count    = unlist(all_reply_counts, use.names = FALSE),
      repost_count   = unlist(all_repost_counts, use.names = FALSE),
      like_count     = unlist(all_like_counts, use.names = FALSE),
      quote_count    = unlist(all_quote_counts, use.names = FALSE),
      bookmark_count = unlist(all_bookmark_counts, use.names = FALSE),
      view_count     = unlist(all_view_counts, use.names = FALSE),
      conversation_id = unlist(all_conversation_ids, use.names = FALSE),
      is_reply       = unlist(all_is_replies, use.names = FALSE),
      is_repost      = unlist(all_is_reposts, use.names = FALSE),
      is_quote       = unlist(all_is_quotes, use.names = FALSE),
      reply_to_post_id = unlist(all_reply_to_ids, use.names = FALSE),
      quoted_post_id   = unlist(all_quoted_ids, use.names = FALSE),
      # Entity fields (Task 56)
      hashtags       = unlist(all_hashtags, recursive = FALSE),
      mentions       = unlist(all_mentions, recursive = FALSE),
      urls           = unlist(all_urls, recursive = FALSE)
    )
  } else {
    merged_posts <- list(
      post_id        = character(0),
      text           = character(0),
      author_id      = character(0),
      username       = character(0),
      display_name   = character(0),
      created_at     = character(0),
      reply_count    = integer(0),
      repost_count   = integer(0),
      like_count     = integer(0),
      quote_count    = integer(0),
      bookmark_count = integer(0),
      view_count     = integer(0),
      conversation_id = character(0),
      is_reply       = logical(0),
      is_repost      = logical(0),
      is_quote       = logical(0),
      reply_to_post_id = character(0),
      quoted_post_id   = character(0),
      # Entity fields (Task 56)
      hashtags       = list(),
      mentions       = list(),
      urls           = list()
    )
  }

  # 7b. Observation-level provenance.
  n_merged <- if (length(merged_posts$post_id) > 0L) length(merged_posts$post_id) else 0L
  merged_posts$collected_at     <- rep(format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), n_merged)
  merged_posts$collection_query <- rep(paste0("@", trimws(username)), n_merged)
  merged_posts$collection_id    <- rep(collection_id, n_merged)

  # 8. Normalize, convert to tibble, deduplicate.
  normalized <- .rx_normalize_posts(merged_posts)
  tibble_posts <- .rx_normalized_to_tibble(normalized)
  deduped <- .rx_deduplicate_posts(tibble_posts)

  # 9. Apply limit.
  if (!is.null(limit) && nrow(deduped) > limit) {
    deduped <- deduped[seq_len(limit), , drop = FALSE]
  }

  # 10. Clean up network capture.
  .rx_search_cleanup(backend)

  # 10b. Write checkpoint for resume support.
  if (isTRUE(resume) && !is.null(jsonl_path)) {
    checkpoint <- .rx_checkpoint_from_state(state, collection_id, paste0("@", trimws(username)))
    tryCatch(
      {
        .rx_checkpoint_write(jsonl_path, checkpoint)
        .rx_progress("Checkpoint saved to ", jsonl_path, quiet = quiet)
      },
      error = function(e) {
        warning("Failed to write checkpoint to '", jsonl_path, "': ", e$message)
      }
    )
  }

  # 11. Attach collection provenance metadata.
  provenance <- .rx_collection_metadata(
    collection_id = collection_id,
    started_at = collection_started_at,
    query = paste0("@", trimws(username)),
    backend = backend_label,
    record_count = as.integer(nrow(deduped))
  )
  attr(deduped, "rx_collection_provenance") <- provenance

  .rx_progress(
    "Collection complete: ", nrow(deduped), " post(s) in ",
    round(as.numeric(difftime(Sys.time(), collection_started_at, units = "secs")), 1),
    "s",
    quiet = quiet
  )

  deduped
}
